# Generated by Django 5.1.1 on 2024-11-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_signup_remove_organization_address_and_more'),
        ('Home', '0005_auto_20241118_2320'),
    ]

    operations = [
    ]
