# Generated by Django 5.1.1 on 2024-11-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='org_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
