# Generated by Django 5.1.1 on 2024-11-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_customuser_org_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='org_id',
        ),
    ]
