# Generated by Django 3.1.12 on 2024-12-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_remove_customuser_org_id'),
        ('Home', '0014_alter_employeesignu_unique_id'),
    ]

    operations = [
    ]
