# Generated by Django 3.1.12 on 2024-12-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_auto_20241221_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7),
        ),
    ]
