# Generated by Django 3.1.12 on 2024-12-21 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_organization_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
