# Generated by Django 3.1.12 on 2024-12-21 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
