# Generated by Django 3.1.12 on 2024-12-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0022_auto_20241221_1726'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesignu',
            old_name='Unique_id',
            new_name='unique_id',
        ),
        migrations.AddField(
            model_name='employeesignu',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees_photos/'),
        ),
    ]
