# Generated by Django 5.1.6 on 2025-02-25 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0024_employeesignup_delete_employeesignu_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesignup',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employee_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='employee_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='query',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=8),
        ),
    ]
