# Generated by Django 5.1.6 on 2025-02-28 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0025_employeesignup_groups_employeesignup_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeesignup',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='Home.organization'),
        ),
        migrations.AddField(
            model_name='query',
            name='owner',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='Home.organization'),
            preserve_default=False,
        ),
    ]
