# Generated by Django 5.1.6 on 2025-02-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0027_alter_employeesignup_organization'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupRequest',
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default=123, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organization',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='organization_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='organization',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='organization',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='organization_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='employee_signup_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='employeesignup',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='employee_signup_permissions', to='auth.permission'),
        ),
    ]
