# Generated by Django 5.1.6 on 2025-02-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0029_alter_employeesignup_unique_id_organizationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default='0aa8f9afaef1', editable=False, max_length=12, unique=True),
        ),
    ]
