# Generated by Django 5.1.6 on 2025-03-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0031_alter_employeesignup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default='2f8629f197d7', editable=False, max_length=12, unique=True),
        ),
    ]
