# Generated by Django 5.1.6 on 2025-03-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0032_alter_employeesignup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default='b0f04cfa8b0f', editable=False, max_length=12, unique=True),
        ),
    ]
