# Generated by Django 5.1.6 on 2025-03-03 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0033_alter_employeesignup_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default='aa76cc89c4c0', editable=False, max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtoken',
            name='key',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='organizationtoken',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Home.organization'),
        ),
    ]
