# Generated by Django 5.1.6 on 2025-03-03 11:20

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0034_alter_employeesignup_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='unique_id',
            field=models.CharField(default=Home.models.generate_uuid, editable=False, max_length=12, unique=True),
        ),
        migrations.DeleteModel(
            name='OrganizationToken',
        ),
    ]
