# Generated by Django 5.1.6 on 2025-03-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Home", "0035_alter_employeesignup_unique_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RFIDCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_uid", models.CharField(max_length=50, unique=True)),
                ("scanned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
